<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="WS_GESTIONE_CLIENTI_PUB"
     targetNamespace="http://www.skytv.it/mdw/service/WS_GESTIONE_CLIENTI_PUB"
     xmlns:tns="http://www.skytv.it/mdw/service/WS_GESTIONE_CLIENTI_PUB"
     xmlns:inp1="http://www.skytv.it/mdw/data"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
     xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
    <wsdl:types>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="http://www.skytv.it/mdw/data" schemaLocation="../xsd/XSD_GESTIONE_CLIENTI_PUB.xsd"/>
            <xsd:import namespace="http://www.skytv.it/mdw/data" schemaLocation="../../../../EnterpriseObjects/CommonEntities/SoapHeaderSKY.xsd"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="requestMessage">
        <wsdl:part name="part_in_CambioCodiceFiscale" element="inp1:requestCambioCodiceFiscale"/>
    </wsdl:message>
    <wsdl:message name="replyMessage">
        <wsdl:part name="part_out_CambioCodiceFiscale" element="inp1:responseCambioCodiceFiscale"/>
    </wsdl:message>
    <wsdl:portType name="WS_GESTIONE_CLIENTI_PUB_ptt">
        <wsdl:operation name="execute_CambioCodiceFiscale">
            <wsdl:input message="tns:requestMessage"/>
            <wsdl:output message="tns:replyMessage"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="WS_GESTIONE_CLIENTI_PUB_bind" type="tns:WS_GESTIONE_CLIENTI_PUB_ptt">
        <soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="execute_CambioCodiceFiscale">
            <soap:operation style="document" soapAction="execute_CambioCodiceFiscale"/>
            <wsdl:input>
                <soap:body use="literal" namespace="http://www.skytv.it/mdw/service/WS_GESTIONE_CLIENTI_PUB"/>
                <soap:header message="tns:Header_Message" part="part_Header" use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal" namespace="http://www.skytv.it/mdw/service/WS_GESTIONE_CLIENTI_PUB"/>
                <soap:header message="tns:Header_Message" part="part_Header" use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:message name="Header_Message">
        <wsdl:part name="part_Header" element="inp1:Header"/>
    </wsdl:message>
</wsdl:definitions>