<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:tns="http://www.skytv.it/mdw/service/CRM_EGON_NORMALIZZA_INDIRIZZO" xmlns:inp1="http://www.skytv.it/mdw/data" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" name="WS_CRM_EGON_NORMALIZZA_INDIRIZZO" targetNamespace="http://www.skytv.it/mdw/service/CRM_EGON_NORMALIZZA_INDIRIZZO">
	<wsdl:types>
		<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
			<xsd:import namespace="http://www.skytv.it/mdw/data" schemaLocation="../xsd/XSD_CRM_EGON_NORMALIZZA_INDIRIZZO.xsd"/>
			<xsd:import namespace="http://www.skytv.it/mdw/data" schemaLocation="../../../../EnterpriseObjects/CommonEntities/SoapHeaderSKY.xsd"/>
		</xsd:schema>
	</wsdl:types>
	<wsdl:message name="requestNormalizzaIndirizzo_message">
		<wsdl:part name="part_requestNormalizzaIndirizzo" element="inp1:requestNormalizzaIndirizzo"/>
	</wsdl:message>
	<wsdl:message name="responseNormalizzaIndirizzo_message">
		<wsdl:part name="part_responseNormalizzaIndirizzo" element="inp1:responseNormalizzaIndirizzo"/>
	</wsdl:message>
	<wsdl:message name="header_message">
		<wsdl:part name="part_header" element="inp1:Header"/>
	</wsdl:message>
	<wsdl:portType name="CRM_EGON_NORMALIZZA_INDIRIZZO_ptt">
		<wsdl:operation name="execute_NormalizzaIndirizzo">
			<wsdl:input message="tns:requestNormalizzaIndirizzo_message"/>
			<wsdl:output message="tns:responseNormalizzaIndirizzo_message"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="CRM_EGON_NORMALIZZA_INDIRIZZO_pttSOAP11Binding" type="tns:CRM_EGON_NORMALIZZA_INDIRIZZO_ptt">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="execute_NormalizzaIndirizzo">
			<soap:operation soapAction="http://www.skytv.it/mdw/service/CRM_EGON_NORMALIZZA_INDIRIZZO/execute_NormalizzaIndirizzo" style="document"/>
			<wsdl:input>
				<soap:body parts="part_requestNormalizzaIndirizzo" use="literal"/>
				<soap:header message="tns:header_message" part="part_header" use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body parts="part_responseNormalizzaIndirizzo" use="literal"/>
				<soap:header message="tns:header_message" part="part_header" use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
</wsdl:definitions>