<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:tns="http://www.skytv.it/mdw/service/CRM_SIE_GET_STORICO_ODL" xmlns:inp1="http://www.skytv.it/mdw/data" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" name="WS_CRM_SIE_GET_STORICO_ODL" targetNamespace="http://www.skytv.it/mdw/service/CRM_SIE_GET_STORICO_ODL">
	<wsdl:types>
		<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
			<xsd:import namespace="http://www.skytv.it/mdw/data" schemaLocation="../xsd/XSD_CRM_SIE_GET_STORICO_ODL.xsd"/>
			<xsd:import namespace="http://www.skytv.it/mdw/data" schemaLocation="../../../../EnterpriseObjects/CommonEntities/SoapHeaderSKY.xsd"/>
		</xsd:schema>
	</wsdl:types>
	<wsdl:message name="responseGetStoricoODL_message">
		<wsdl:part name="part_requestGetStoricoODL" element="inp1:requestGetStoricoODL"/>
	</wsdl:message>
	<wsdl:message name="requestGetStoricoODL_message">
		<wsdl:part name="part_responseGetStoricoODL" element="inp1:responseGetStoricoODL"/>
	</wsdl:message>
	<wsdl:message name="header_message">
		<wsdl:part name="part_header" element="inp1:Header"/>
	</wsdl:message>
	<wsdl:portType name="CRM_SIE_GET_STORICO_ODL_ptt">
		<wsdl:operation name="execute_GetStoricoODL">
			<wsdl:input message="tns:responseGetStoricoODL_message"/>
			<wsdl:output message="tns:requestGetStoricoODL_message"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="CRM_SIE_GET_STORICO_ODL_pttSOAP11Binding" type="tns:CRM_SIE_GET_STORICO_ODL_ptt">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="execute_GetStoricoODL">
			<soap:operation soapAction="http://www.skytv.it/mdw/service/CRM_SIE_GET_STORICO_ODL/execute_GetStoricoODL" style="document"/>
			<wsdl:input>
				<soap:body parts="part_requestGetStoricoODL" use="literal"/>
				<soap:header message="tns:header_message" part="part_header" use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body parts="part_responseGetStoricoODL" use="literal"/>
				<soap:header message="tns:header_message" part="part_header" use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
</wsdl:definitions>