<wsdl:definitions name="PS_REST_DYNAMIC_ELEMENTS" targetNamespace="http://xmlns.oracle.com/OSB_SVIL/TestMario/PS_REST_DYNAMIC_ELEMENTS" xmlns:tns="http://xmlns.oracle.com/OSB_SVIL/TestMario/PS_REST_DYNAMIC_ELEMENTS" xmlns:inp1="http://www.example.org" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <plnk:partnerLinkType name="PS_REST_DYNAMIC_ELEMENTS">
        <plnk:role name="PS_REST_DYNAMIC_ELEMENTSProvider" portType="tns:PS_REST_DYNAMIC_ELEMENTS_ptt"/>
    </plnk:partnerLinkType>
    <wsdl:types>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="http://www.example.org" schemaLocation="../DynamicElements/xsd/XSD_DYNAMIC_ELEMENTS.xsd"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="OpDynElements_inputMessage">
        <wsdl:part name="request" element="inp1:requestDynamicElements"/>
    </wsdl:message>
    <wsdl:message name="Rest_EmptyMessage"/>
    <wsdl:portType name="PS_REST_DYNAMIC_ELEMENTS_ptt">
        <wsdl:operation name="OpDynElements">
            <wsdl:input message="tns:OpDynElements_inputMessage"/>
            <wsdl:output message="tns:Rest_EmptyMessage"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="PS_REST_DYNAMIC_ELEMENTS_ptt-binding" type="tns:PS_REST_DYNAMIC_ELEMENTS_ptt">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="OpDynElements">
            <soap:operation soapAction="OpDynElements"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>