<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:tns="http://www.skytv.it/mdw/service/OM_GET_ORDER_PAYMENT" xmlns:inp1="http://www.skytv.it/mdw/data" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" name="WS_OM_GET_ORDER_PAYMENT" targetNamespace="http://www.skytv.it/mdw/service/OM_GET_ORDER_PAYMENT">
	<wsdl:types>
		<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
			<xsd:import namespace="http://www.skytv.it/mdw/data" schemaLocation="../xsd/XSD_OM_GET_ORDER_PAYMENT.xsd"/>
			<xsd:import namespace="http://www.skytv.it/mdw/data" schemaLocation="../../../../EnterpriseObjects/CommonEntities/SoapHeaderSKY.xsd"/>
		</xsd:schema>
	</wsdl:types>
	<wsdl:message name="requestGetOrderPayment_message">
		<wsdl:part name="part_requestGetOrderPayment" element="inp1:requestGetOrderPayment"/>
	</wsdl:message>
	<wsdl:message name="responseGetOrderPayment_message">
		<wsdl:part name="part_responseGetOrderPayment" element="inp1:responseGetOrderPayment"/>
	</wsdl:message>
	<wsdl:message name="header_message">
		<wsdl:part name="part_header" element="inp1:Header"/>
	</wsdl:message>
	<wsdl:portType name="OM_GET_ORDER_PAYMENT_ptt">
		<wsdl:operation name="execute_GetOrderPayment">
			<wsdl:input message="tns:requestGetOrderPayment_message"/>
			<wsdl:output message="tns:responseGetOrderPayment_message"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="OM_GET_ORDER_PAYMENT_pttSOAP11Binding" type="tns:OM_GET_ORDER_PAYMENT_ptt">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="execute_GetOrderPayment">
			<soap:operation soapAction="http://www.skytv.it/mdw/service/OM_GET_ORDER_PAYMENT/execute_GetOrderPayment" style="document"/>
			<wsdl:input>
				<soap:body parts="part_requestGetOrderPayment" use="literal"/>
				<soap:header message="tns:header_message" part="part_header" use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body parts="part_responseGetOrderPayment" use="literal"/>
				<soap:header message="tns:header_message" part="part_header" use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
</wsdl:definitions>