<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="WS_CRM_GET_PACCHETTI_RETENTION"
     targetNamespace="http://www.skytv.it/mdw/service/CRM_GET_PACCHETTI_RETENTION"
     xmlns:tns="http://www.skytv.it/mdw/service/CRM_GET_PACCHETTI_RETENTION"
     xmlns:inp1="http://www.skytv.it/mdw/data"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
     xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
    <wsdl:types>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="http://www.skytv.it/mdw/data" schemaLocation="../xsd/XSD_CRM_GET_PACCHETTI_RETENTION.xsd"/>
            <xsd:import namespace="http://www.skytv.it/mdw/data" schemaLocation="../../../../EnterpriseObjects/CommonEntities/SoapHeaderSKY.xsd"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="requestGetPacchettiRetention_Message">
        <wsdl:part name="part_requestGetPacchettiRetention" element="inp1:requestGetPacchettiRetention"/>
    </wsdl:message>
    <wsdl:message name="responseGetPacchettiRetention_Message">
        <wsdl:part name="part_responseGetPacchettiRetention" element="inp1:responseGetPacchettiRetention"/>
    </wsdl:message>
    <wsdl:portType name="CRM_GET_PACCHETTI_RETENTION_ptt">
        <wsdl:operation name="execute_GetPacchettiRetention">
            <wsdl:input message="tns:requestGetPacchettiRetention_Message"/>
            <wsdl:output message="tns:responseGetPacchettiRetention_Message"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="CRM_GET_PACCHETTI_RETENTION_bind" type="tns:CRM_GET_PACCHETTI_RETENTION_ptt">
        <soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="execute_GetPacchettiRetention">
            <soap:operation style="document" soapAction="execute_GetPacchettiRetention"/>
            <wsdl:input>
                <soap:body use="literal" namespace="http://www.skytv.it/mdw/service/CRM_GET_PACCHETTI_RETENTION"/>
                <soap:header message="tns:header_Message" part="part_Header" use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal" namespace="http://www.skytv.it/mdw/service/CRM_GET_PACCHETTI_RETENTION"/>
                <soap:header message="tns:header_Message" part="part_Header" use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:message name="header_Message">
        <wsdl:part name="part_Header" element="inp1:Header"/>
    </wsdl:message>
</wsdl:definitions>