<wsdl:definitions xmlns:tns="http://www.skytv.it/mdw/service/CRM_CTI_SUBMITTER_BATCH" xmlns:inp1="http://www.skytv.it/mdw/data" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" name="WS_CRM_CTI_SUBMITTER_BATCH" targetNamespace="http://www.skytv.it/mdw/service/CRM_CTI_SUBMITTER_BATCH">
	<wsdl:types>
		<xsd:schema>
			<xsd:import namespace="http://www.skytv.it/mdw/data" schemaLocation="../xsd/XSD_CRM_CTI_SUBMITTER_BATCH.xsd"/>
			<xsd:import namespace="http://www.skytv.it/mdw/data" schemaLocation="../../../../EnterpriseObjects/CommonEntities/SoapHeaderSKY.xsd"/>
		</xsd:schema>
	</wsdl:types>
	<wsdl:message name="requestMessage">
		<wsdl:part name="part_requestSubmitterBatch" element="inp1:requestSubmitterBatch"/>
	</wsdl:message>
	<wsdl:message name="replyMessage">
		<wsdl:part name="part_responseSubmitterBatch" element="inp1:responseSubmitterBatch"/>
	</wsdl:message>
	<wsdl:message name="Header_Message">
		<wsdl:part name="part_HeaderMessage" element="inp1:Header"/>
	</wsdl:message>
	<wsdl:portType name="CRM_CTI_SUBMITTER_BATCH_ptt">
		<wsdl:operation name="execute_SubmitterBatch">
			<wsdl:input message="tns:requestMessage"/>
			<wsdl:output message="tns:replyMessage"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="CRM_CTI_SUBMITTER_BATCH_bind" type="tns:CRM_CTI_SUBMITTER_BATCH_ptt">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="execute_SubmitterBatch">
			<soap:operation soapAction="http://www.skytv.it/mdw/service/CRM_CTI_SUBMITTER_BATCH/execute_SubmitterBatch" style="document"/>
			<wsdl:input>
				<soap:body parts="part_requestSubmitterBatch" use="literal"/>
				<soap:header message="tns:Header_Message" part="part_HeaderMessage" use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body parts="part_responseSubmitterBatch" use="literal"/>
				<soap:header message="tns:Header_Message" part="part_HeaderMessage" use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
</wsdl:definitions>