<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:mdata="http://www.skytv.it/mdw/data" xmlns:tns="http://www.skytv.it/mdw/service/CRM_GESTIONE_PAG_SISAL" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" name="WS_CRM_GESTIONE_PAG_SISAL" targetNamespace="http://www.skytv.it/mdw/service/CRM_GESTIONE_PAG_SISAL">
	<wsdl:types>
		<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
			<xsd:import namespace="http://www.skytv.it/mdw/data" schemaLocation="../xsd/XSD_CRM_GESTIONE_PAG_SISAL.xsd"/>
			<xsd:import namespace="http://www.skytv.it/mdw/data" schemaLocation="../../../../EnterpriseObjects/CommonEntities/SoapHeaderSKY.xsd"/>
		</xsd:schema>
	</wsdl:types>
	<wsdl:message name="requestREPASI_Message">
		<wsdl:part name="part_requestREPASI" element="mdata:requestREPASI"/>
	</wsdl:message>
	<wsdl:message name="responseREPASI_Message">
		<wsdl:part name="part_responseREPASI" element="mdata:responseREPASI"/>
	</wsdl:message>
	<wsdl:message name="Header_Message">
		<wsdl:part name="part_HeaderMessage" element="mdata:Header"/>
	</wsdl:message>
	<wsdl:portType name="CRM_GESTIONE_PAG_SISAL_ptt">
		<wsdl:operation name="execute_REPASI">
			<wsdl:input message="tns:requestREPASI_Message"/>
			<wsdl:output message="tns:responseREPASI_Message"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="CRM_GESTIONE_PAG_SISAL_bind" type="tns:CRM_GESTIONE_PAG_SISAL_ptt">
		<soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="execute_REPASI">
			<soap:operation soapAction="http://www.skytv.it/mdw/service/CRM_GESTIONE_PAG_SISAL/execute_REPASI" style="document"/>
			<wsdl:input>
				<soap:body parts="part_requestREPASI" use="literal"/>
				<soap:header message="tns:Header_Message" part="part_HeaderMessage" use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body parts="part_responseREPASI" use="literal"/>
				<soap:header message="tns:Header_Message" part="part_HeaderMessage" use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
</wsdl:definitions>