<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="WS_CRM_CALCOLA_MGM"
     targetNamespace="http://www.skytv.it/mdw/service/CRM_CALCOLA_MGM"
     xmlns:tns="http://www.skytv.it/mdw/service/CRM_CALCOLA_MGM"
     xmlns:inp1="http://www.skytv.it/mdw/data"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
     xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
    <wsdl:types>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="http://www.skytv.it/mdw/data" schemaLocation="../xsd/XSD_CRM_CALCOLA_MGM.xsd"/>
            <xsd:import namespace="http://www.skytv.it/mdw/data" schemaLocation="../../../../EnterpriseObjects/CommonEntities/SoapHeaderSKY.xsd"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="requestCalcolaMGM_Message">
        <wsdl:part name="part_requestCalcolaMGM" element="inp1:requestCalcolaMGM"/>
    </wsdl:message>
    <wsdl:message name="responseCalcolaMGM_Message">
        <wsdl:part name="part_responseCalcolaMGM" element="inp1:responseCalcolaMGM"/>
    </wsdl:message>
    <wsdl:portType name="CRM_CALCOLA_MGM_ptt">
        <wsdl:operation name="execute_calcolaMGM">
            <wsdl:input message="tns:requestCalcolaMGM_Message"/>
            <wsdl:output message="tns:responseCalcolaMGM_Message"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="CRM_CALCOLA_MGM_bind" type="tns:CRM_CALCOLA_MGM_ptt">
        <soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="execute_calcolaMGM">
            <soap:operation style="document" soapAction="execute_calcolaMGM"/>
            <wsdl:input>
                <soap:body use="literal" namespace="http://www.skytv.it/mdw/service/CRM_CALCOLA_MGM"/>
                <soap:header message="tns:header_Message" part="part_header" use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal" namespace="http://www.skytv.it/mdw/service/CRM_CALCOLA_MGM"/>
                <soap:header message="tns:header_Message" part="part_header" use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:message name="header_Message">
        <wsdl:part name="part_header" element="inp1:Header"/>
    </wsdl:message>
</wsdl:definitions>