<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:tns="http://www.skytv.it/mdw/service/CRM_RESET_SMC" xmlns:inp1="http://www.skytv.it/mdw/data" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" name="WS_CRM_RESET_SMC" targetNamespace="http://www.skytv.it/mdw/service/CRM_RESET_SMC">
	<wsdl:types>
		<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
			<xsd:import namespace="http://www.skytv.it/mdw/data" schemaLocation="../xsd/XSD_CRM_RESET_SMC.xsd"/>
			<xsd:import namespace="http://www.skytv.it/mdw/data" schemaLocation="../../../../EnterpriseObjects/CommonEntities/SoapHeaderSKY.xsd"/>
		</xsd:schema>
	</wsdl:types>
	<wsdl:message name="requestResetSmc_Message">
		<wsdl:part name="part_requestResetSmc" element="inp1:requestResetSmc"/>
	</wsdl:message>
	<wsdl:message name="responseResetSmc_Message">
		<wsdl:part name="part_responseResetSmc" element="inp1:responseResetSmc"/>
	</wsdl:message>
	<wsdl:message name="header_Message">
		<wsdl:part name="part_header" element="inp1:Header"/>
	</wsdl:message>
	<wsdl:portType name="CRM_RESET_SMC_ptt">
		<wsdl:operation name="execute_ResetSmc">
			<wsdl:input message="tns:requestResetSmc_Message"/>
			<wsdl:output message="tns:responseResetSmc_Message"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="CRM_RESET_SMC_bind" type="tns:CRM_RESET_SMC_ptt">
		<soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="execute_ResetSmc">
			<soap:operation soapAction="execute_ResetSmc" style="document"/>
			<wsdl:input>
				<soap:body use="literal" namespace="http://www.skytv.it/mdw/service/CRM_RESET_SMC"/>
				<soap:header message="tns:header_Message" part="part_header" use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal" namespace="http://www.skytv.it/mdw/service/CRM_RESET_SMC"/>
				<soap:header message="tns:header_Message" part="part_header" use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
</wsdl:definitions>