<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:tns="http://www.skytv.it/mdw/service/SIE_ADESIONE_PROMO_STB" xmlns:inp1="http://www.skytv.it/mdw/data" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" name="WS_SIE_ADESIONE_PROMO_STB" targetNamespace="http://www.skytv.it/mdw/service/SIE_ADESIONE_PROMO_STB">
	<wsdl:types>
		<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
			<xsd:import namespace="http://www.skytv.it/mdw/data" schemaLocation="../xsd/XSD_SIE_ADESIONE_PROMO_STB.xsd"/>
			<xsd:import namespace="http://www.skytv.it/mdw/data" schemaLocation="../../../../EnterpriseObjects/CommonEntities/SoapHeaderSKY.xsd"/>
		</xsd:schema>
	</wsdl:types>
	<wsdl:message name="requestAdesionePromoSTB_message">
		<wsdl:part name="part_requestAdesionePromoSTB" element="inp1:requestAdesionePromoSTB"/>
	</wsdl:message>
	<wsdl:message name="responseAdesionePromoSTB_message">
		<wsdl:part name="part_responseAdesionePromoSTB" element="inp1:responseAdesionePromoSTB"/>
	</wsdl:message>
	<wsdl:message name="header_message">
		<wsdl:part name="part_header" element="inp1:Header"/>
	</wsdl:message>
	<wsdl:portType name="SIE_ADESIONE_PROMO_STB_ptt">
		<wsdl:operation name="execute_AdesionePromoSTB">
			<wsdl:input message="tns:requestAdesionePromoSTB_message"/>
			<wsdl:output message="tns:responseAdesionePromoSTB_message"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="SIE_ADESIONE_PROMO_STB_pttSOAP11Binding" type="tns:SIE_ADESIONE_PROMO_STB_ptt">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="execute_AdesionePromoSTB">
			<soap:operation soapAction="http://www.skytv.it/mdw/service/SIE_ADESIONE_PROMO_STB/execute_AdesionePromoSTB" style="document"/>
			<wsdl:input>
				<soap:body parts="part_requestAdesionePromoSTB" use="literal"/>
				<soap:header message="tns:header_message" part="part_header" use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body parts="part_responseAdesionePromoSTB" use="literal"/>
				<soap:header message="tns:header_message" part="part_header" use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
</wsdl:definitions>