<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="WS_SF_ADDITIONAL_SERVICES"
     targetNamespace="http://www.skytv.it/mdw/service/WS_SF_ADDITIONAL_SERVICES"
     xmlns:tns="http://www.skytv.it/mdw/service/WS_SF_ADDITIONAL_SERVICES"
     xmlns:inp1="http://www.skytv.it/mdw/data"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
     xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
    <wsdl:types>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="http://www.skytv.it/mdw/data" schemaLocation="../xsd/XSD_SF_ADDITIONAL_SERVICES_HANDLER.xsd"/>
            <xsd:import namespace="http://www.skytv.it/mdw/data" schemaLocation="../../../../../EnterpriseObjects/CommonEntities/SoapHeaderSKY.xsd"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="requestMessage">
        <wsdl:part name="part_RequestAddAdditionalServices" element="inp1:requestAddAdditionalServices"/>
    </wsdl:message>
    <wsdl:message name="replyMessage">
        <wsdl:part name="part_responseAddAdditionalServices" element="inp1:responseAddAdditionalServices"/>
    </wsdl:message>
    <wsdl:message name="headerMessage">
        <wsdl:part name="part_header" element="inp1:Header"/>
    </wsdl:message>    
    <wsdl:portType name="ptt_SF_ADDITIONAL_SERVICES">
        <wsdl:operation name="execute_AddAdditionalServices">
            <wsdl:input message="tns:requestMessage"/>
            <wsdl:output message="tns:replyMessage"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="bind_SF_ADDITIONAL_SERVICES" type="tns:ptt_SF_ADDITIONAL_SERVICES">
        <soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="execute_AddAdditionalServices">
            <soap:operation style="document" soapAction="execute_AddAdditionalServices"/>
            <wsdl:input>
                <soap:header message="tns:headerMessage" part="part_header" use="literal"/>
                <soap:body use="literal" namespace="http://www.skytv.it/mdw/service/WS_SF_ADDITIONAL_SERVICES" parts="part_RequestAddAdditionalServices"/>
            </wsdl:input>
            <wsdl:output>
                <soap:header message="tns:headerMessage" part="part_header" use="literal"/>
                <soap:body use="literal" namespace="http://www.skytv.it/mdw/service/WS_SF_ADDITIONAL_SERVICES" parts="part_responseAddAdditionalServices"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>